### ISSUE TITLE
转换异常

### ISSUE THREAD

**Issue by Nov3n** [chr233/WinAuth2SDA#1]
在两台电脑上都试过了，不行，异常贴在下面了
```
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.InvalidCastException: Null object cannot be converted to a value type.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(JsonReader reader, Object value, CultureInfo culture, JsonContract contract, Type targetType)


************** 已加载的程序集 **************
System.Private.CoreLib
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
WinAuth2SDA
    程序集版本:1.0.2.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.InteropServices
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Specialized
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.TraceSource
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing.Common
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.EventBasedAsync
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.Thread
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Accessibility
    程序集版本:4.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel.TypeConverter
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Memory
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Numerics.Vectors
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Microsoft.Win32.SystemEvents
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Concurrent
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ComponentModel
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Resources.Extensions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Drawing
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.ObjectModel
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.NonGeneric
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Configuration.ConfigurationManager
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Private.Uri
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.Process
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Security.Cryptography
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Xml.ReaderWriter
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Private.Xml
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Net.WebClient
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Text.Encoding.Extensions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Serialization.Formatters
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Xml.XmlSerializer
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Newtonsoft.Json
    程序集版本:13.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Linq.Expressions
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Numerics
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Serialization.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Data.Common
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Emit.ILGeneration
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Emit.Lightweight
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Primitives
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    程序集版本:0.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Threading.ThreadPool
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Runtime.Loader
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Windows.Forms.resources
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Diagnostics.StackTrace
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Reflection.Metadata
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------
System.Collections.Immutable
    程序集版本:7.0.0.0
    Win32 版本:不可用
    代码库:
----------------------------------------

************** JIT 调试 **************
```

**Comment by Nov3n** [comment]
是因为没有vs运行环境吗？

**Comment by chr233** [comment]
什么版本，有截图吗
是fde后缀的版本吗

**Comment by moe001** [comment]
相同问题 winauth3.5.1+sda最新版 没有开加密

**Comment by chr233** [comment]
> 相同问题 winauth3.5.1+sda最新版 没有开加密

q1142033406 远程看看

**Comment by chr233** [comment]
请提供联系方式，远程帮解决

**Comment by nxs333** [comment]
我也是同样的报错，，好像是账号有下划线或者什么，符号报错，，多个号，只能转换成功一个

**Comment by chr233** [comment]
应该修了？
试试1.0.3.0，改善了一下兼容性，主要winauth保存的值很多时候不完整
